ARG IMAGE_VERSION=6.0-alpine

FROM openjdk:8u131-jre-alpine

MAINTAINER Jean-Michel Ruiz <jean.ruiz@cismet.de>


# STUFF

RUN apk update && apk add --no-cache curl zip unzip nginx vim

# MAVEN

ENV MAVEN_MIRROR http://www-eu.apache.org/dist/maven/maven-3/
ENV MAVEN_LIB_DIR ${LIB_DIR}/m2
ENV MAVEN_OPTS -XX:-OmitStackTraceInFastThrow -server -Xms512m -Xmx1024m
ENV MAVEN_VERSION 3.5.2
ENV MAVEN_HOME /usr/share/maven

RUN mkdir -p ${MAVEN_HOME} \
    && curl -fsSL ${MAVEN_MIRROR}/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz | tar -xzC ${MAVEN_HOME} --strip-components=1 \
    && ln -s ${MAVEN_HOME}/bin/mvn /usr/bin/mvn

# ===

LABEL de.cismet.cids.java.maven.name="cids-distribution-base ${IMAGE_VERSION} runtime image" \
      de.cismet.cids.java.maven.version="cids-distribution-base ${IMAGE_VERSION} jdk-1.8u131-jdk" \
      de.cismet.cids.java.maven.tag.docker="cids-distribution-base ${IMAGE_VERSION} jdk-1.8u131-jdk" \
      de.cismet.cids.java.maven.tag.git="cids-distribution-base ${IMAGE_VERSION} jdk-1.8u131-jdk" \
      de.cismet.cids.java.maven.description="Java and Maven Runtime Image" 
